config/routes.rb
Rails.application.routes.draw do
  # get 'student/index'
  root 'students#index'
  resources :students do
    resources :comments
  end
  #get 'students/index'
  # get 'students/new'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end
class Student < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @student = Student.find(params[:student_id])
        @comment = @student.comments.create(comment_params)
        redirect_to student_path(@student)
      end
      def show
        @student = Student.find(params[:student_id])
        @comment = Comment.new
      end
    
      def edit
        @comment = Comment.find(params[:student_id])
      end
      def update
        @student = Student.find(params[:id])
        @comment = Comment.find(params[:student_id])
    
        if @comment.update(comment_params)
          redirect_to student_path(params[:id])
        else
          render :edit
        end
      end
      
    
      def destroy
        @student = Student.find(params[:student_id])
        @comment = @student.comments.find(params[:id])
        @comment.destroy
        redirect_to student_path(@student), status: :see_other
      end
    
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
 
  
  def index
    @students = Student.all
  end

 def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path, notice: 'Student has been created successfully'
    else
      render :new
    end
  end

  def show
    @student = Student.find(params[:id])
  end
  
  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to student_path(@student), notice: 'Student has been updated successfully'
    else
      render :edit
  end
end

def destroy
  @student = Student.find(params[:id])
  @student.destroy
  redirect_to students_path, notice: 'Student has been deleted successfully'
end

private
def student_params
  params.require(:student).permit(:f_name, :l_name, :email, :phone_no, :bio)
end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/comments/edit.html.erb
<%= form_for @comment, url: student_comment_path, method: :PATCH do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
  <%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>College</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%=  form_with model: student do |form|  %>

    
        
        
        
    <div>
    <%= form.label  :f_name %>
    </br>
    <%= form.text_field :f_name %>
    
    </div>

    <div>
    <%= form.label  :l_name %><br>
    <%= form.text_field :l_name %>
    </div>

    <div>
    <%= form.label  :email %></br>
    <%= form.text_field :email %>
    </div>

    <div>
    <%= form.label  :phone_no %></br>
    <%= form.text_field :phone_no %>
    </div>

    <div>
    <%= form.label  :bio %></br>
    <%= form.text_field :bio %>
    </div>

    <div>
    <%= form.submit %></br>
    </div>
    
    <%  end  %>

app/views/students/edit.html.erb
<%=  form_for @student, url: student_path, method: :PATCH do |form|  %>

    
        
        
        
    <div>
    <%= form.label  :f_name %>
    </br>
    <%= form.text_field :f_name %>
    
    </div>

    <div>
    <%= form.label  :l_name %><br>
    <%= form.text_field :l_name %>
    </div>

    <div>
    <%= form.label  :email %></br>
    <%= form.text_field :email %>
    </div>

    <div>
    <%= form.label  :phone_no %></br>
    <%= form.text_field :phone_no %>
    </div>

    <div>
    <%= form.label  :bio %></br>
    <%= form.text_field :bio %>
    </div>

    <div>
    <%= form.submit %></br>
    </div>
    
    <%  end  %>

app/views/students/index.html.erb
<p><%= notice %></p>
<h1> Welcome Students </h1>
<%= link_to 'New Student', new_student_path %>

<% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
<% end %>

<table>
 <thead>
     <tr>
      <th> f_name </th>
      <th> l_name </th>
      <th> email </th>
      <th> phone_no  </th>
      <th> bio </th>
     </tr>
    </thead>
     <tbody>
       <% @students.each do |student| %>
        <tr>
            <td><%= student.f_name %></td>
            <td><%= student.l_name %></td>
            <td><%= student.email%></td>
            <td><%= student.phone_no%></td>
            <td><%= student.bio%></td>
            <td><%= link_to 'Show', student_path(student.id) %></td>
            <td><%= link_to 'Edit', edit_student_path(student.id) %></td>
            <td><%= link_to 'Destroy', student_path(student.id), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></td>
        </tr>
      <% end %>
 </tbody>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>


<%= render "form", student: @student  %>

app/views/students/show.html.erb
<p><%= notice %></p>
<h1>Student Details</h1>
<p><strong>F_Name: </strong><%= @student.try(:f_name) %></p>
<p><strong>L_Name: </strong><%= @student.try(:l_name) %></p>
<p><strong> Email: </strong><%= @student.try(:email) %></p>
<p><strong> Phone_no: </strong><%= @student.try(:phone_no) %></p>
<p><strong> Bio: </strong><%= @student.try(:bio) %></p>

<h1><%= @student.try(:commenter) %></h1>

<p><%= @student.try(:body) %></p>

<ul>
  <li><%= link_to "Edit", edit_student_path(@student) %></li>
  <li><%= link_to "Destroy", student_path(@student), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>



<h2>Comments</h2>
<% @student.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to "Edit", edit_student_comment_path(comment.id) %>
  </p>

  <p>
    <%= link_to "Destroy Comment", [comment.student, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_with model: [ @student, @student.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>